server:
  port: 8889
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: user_service
    user: root
    password: 123456
springdoc:
  show-actuator: true
  api-docs:
    path: endereco-service/v3/api-docs
