server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: endereco-service
        uri: lb://endereco-service
        predicates:
        - Path=/endereco-service/**
      - id: pessoa-service
        uri: lb://pessoa-service
        predicates:
        - Path=/pessoa-service/**
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user-service/**
      - id: opengateway
        uri: lb://gateway-service
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
